spring:
  application:
    name: graphql-demo-for-learning

  datasource:
    url: jdbc:postgresql://localhost:5433/graphql
    username: postgres
    password: karan143
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
